"""empty message

Revision ID: 448742b40b1d
Revises: 3c97b3bc1d49
Create Date: 2022-04-04 11:32:39.878708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448742b40b1d'
down_revision = '3c97b3bc1d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.drop_column('Artist', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
